language: node_js
node_js:
  - "4"
  - "5"
sudo: false
after_script:
 - npm i -g coveralls
 - cat ./coverage/lcov.info | coveralls
services:
  - redis-server
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
